### PR TITLE
Rename magentorootid to rootid.

### LINKED ISSUE #62: change oxrootid to rootid in category data

### PR DESCRIPTION
**Pull request by gyKa**
Closes https://github.com/ongr-io/ongr-sandbox/issues/62 , related to https://github.com/ongr-io/ongr-sandbox/pull/87

### CODE REVIEW

**Comment by GrandLTU** [comment]
Merge with upstream is required.

**Comment by trylika** [comment]
who is doing this? @grandltu?

**Comment by trylika** [comment]
anybody? @gyKa ?

**Comment by gyKa** [comment]
@lmikelionis had made changes for long time ago, so this PR is meaningless.

**Pull request closed without merging**
